project_id = "gtjmfvwkatrorhuyrpby"

[functions.website-chatbot]
verify_jwt = false

[functions.check-order-eligibility]
verify_jwt = false

[functions.track-checkout]
verify_jwt = false

[functions.courier-status]
verify_jwt = false

[functions.customer-trust-score]
verify_jwt = false
